{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":246,"status":"ok","timestamp":1689641277741,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"SesSSx_7QRW4"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-137-b7296996c5fa\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '..')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-137-b7296996c5fa\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '..')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-137-b7296996c5fa\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('cd', '..')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-85\u003e\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["%cd content/drive/MyDrive/SpectrometerLearner2/Zarya/\n","!ls"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"J-1hOm7rQWxf"},"outputs":[],"source":["from csv_processor import CSVProcessor\n","import pandas as pd\n","import numpy as np\n","import tensorflow as tf\n","from tensorflow.keras.models import Sequential\n","from tensorflow.keras.layers import Dense, Dropout, BatchNormalization\n","from sklearn.preprocessing import StandardScaler\n","from sklearn.model_selection import GridSearchCV\n","from sklearn.metrics import accuracy_score\n","from tensorflow.keras.optimizers import Adam\n","from tensorflow.keras.wrappers.scikit_learn import KerasClassifier\n","from keras.layers import Activation"]},{"cell_type":"code","execution_count":109,"metadata":{"executionInfo":{"elapsed":2244,"status":"ok","timestamp":1689642119005,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"9_ItjDe-Zi0b"},"outputs":[],"source":["processor = CSVProcessor(\"../Training Data\")\n","X_train, y_train = processor.split()\n","processor = CSVProcessor(\"../Testing Data\")\n","X_test, y_test = processor.split()"]},{"cell_type":"code","execution_count":112,"metadata":{"executionInfo":{"elapsed":2315,"status":"ok","timestamp":1689642615556,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"9Yia6gneilvm"},"outputs":[],"source":["def apply_data_augmentation(X_train, y_train, num_augmented_samples=1000):\n","    augmented_data = []\n","    augmented_labels = []\n","\n","    for i in range(num_augmented_samples):\n","        # Randomly select an index from the original data\n","        index = np.random.randint(len(X_train))\n","        original_sample = X_train.iloc[index]\n","        label = y_train[index]\n","\n","        # Apply data augmentation (you can customize these operations)\n","        augmented_sample = original_sample + np.random.normal(0, 0.1, original_sample.shape)  # Adding random noise\n","        augmented_sample *= np.random.uniform(0.9, 1.1)  # Scaling by a random factor\n","        if np.random.rand() \u003c 0.5:\n","            augmented_sample = np.flip(augmented_sample)  # Randomly flipping the sample\n","\n","        augmented_data.append(augmented_sample)\n","        augmented_labels.append(label)\n","\n","    # Convert the augmented data and labels to numpy arrays\n","    augmented_data = np.array(augmented_data)\n","    augmented_labels = np.array(augmented_labels)\n","\n","    # Concatenate the original data with the augmented data\n","    X_train_augmented = np.concatenate((X_train.values, augmented_data), axis=0)\n","    y_train_augmented = np.concatenate((y_train, augmented_labels), axis=0)\n","\n","    return X_train_augmented, y_train_augmented\n","\n","# Assuming X_train and y_train are your original data in pandas DataFrames\n","X_train_augmented, y_train_augmented = apply_data_augmentation(X_train.reset_index(drop=True), y_train, num_augmented_samples=1000)"]},{"cell_type":"code","execution_count":116,"metadata":{"executionInfo":{"elapsed":174,"status":"ok","timestamp":1689642672252,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"7sh2xqENhDg9"},"outputs":[],"source":["X_train, y_train = X_train_augmented, y_train_augmented"]},{"cell_type":"code","execution_count":117,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":535,"status":"ok","timestamp":1689642675815,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"GvOmWVPTX4X7","outputId":"d19366f6-1582-4b13-c32b-3f00a3a7bd27"},"outputs":[{"name":"stderr","output_type":"stream","text":["/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but StandardScaler was fitted without feature names\n","  warnings.warn(\n"]}],"source":["scaler = StandardScaler()\n","\n","# Fit the scaler on the training features and transform them\n","X_train_scaled = scaler.fit_transform(X_train)\n","\n","# Transform the test features using the fitted scaler\n","X_test_scaled = scaler.transform(X_test)"]},{"cell_type":"code","execution_count":118,"metadata":{"executionInfo":{"elapsed":185,"status":"ok","timestamp":1689642679216,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"adVgf2AoX4hO"},"outputs":[],"source":["# 4. Split the Data into Training and Test Sets\n","X_train, X_test = X_train_scaled, X_test_scaled"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":1730464,"status":"ok","timestamp":1689639192352,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"7YnQCmXUziZh","outputId":"f8b5ae60-20b6-4cb6-c59f-78e1a99f590e"},"outputs":[{"name":"stderr","output_type":"stream","text":["\u003cipython-input-65-09fc12ef6942\u003e:29: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.\n","  model = KerasClassifier(build_fn=create_model, input_shape=input_shape, num_classes=num_classes, epochs=20, batch_size=32, verbose=0)\n","WARNING:tensorflow:5 out of the last 18 calls to \u003cfunction Model.make_test_function.\u003clocals\u003e.test_function at 0x7fb9a4019cf0\u003e triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n","WARNING:tensorflow:5 out of the last 11 calls to \u003cfunction Model.make_test_function.\u003clocals\u003e.test_function at 0x7fb8e6afa710\u003e triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n"]}],"source":["\"\"\"\n","def create_model(input_shape, num_classes, hidden_layer_sizes=(128,), activation='relu', dropout_rate=0.5, learning_rate=0.001):\n","    model = Sequential()\n","    model.add(Dense(hidden_layer_sizes[0], input_shape=(input_shape,), activation=None))\n","    model.add(BatchNormalization())\n","    model.add(Activation(activation))\n","    model.add(Dropout(dropout_rate))\n","\n","    if len(hidden_layer_sizes) \u003e 1:\n","        for units in hidden_layer_sizes[1:]:\n","            model.add(Dense(units, activation=None))\n","            model.add(BatchNormalization())\n","            model.add(Activation(activation))\n","            model.add(Dropout(dropout_rate))\n","\n","    # Output layer with proper activation based on the number of classes\n","    if num_classes == 1:\n","        model.add(Dense(1, activation='sigmoid'))\n","        loss_function = 'binary_crossentropy'\n","    else:\n","        model.add(Dense(num_classes, activation='softmax'))\n","        loss_function = 'sparse_categorical_crossentropy'\n","\n","    optimizer = Adam(learning_rate=learning_rate)\n","    model.compile(optimizer=optimizer, loss=loss_function, metrics=['accuracy'])\n","\n","    return model  # Return the model.\n","\n","# Create a KerasClassifier with fixed epochs\n","model = KerasClassifier(build_fn=create_model, input_shape=input_shape, num_classes=num_classes, epochs=20, batch_size=32, verbose=0)\n","\n","# Define the hyperparameters and their possible values\n","param_grid = {\n","    'hidden_layer_sizes': [(64,), (128,), (256,), (64, 64), (128, 128), (256, 256)],\n","    'activation': ['relu', 'tanh', 'sigmoid', 'leaky_relu'],\n","    'dropout_rate': [0.2, 0.3, 0.4],\n","    'learning_rate': [0.001, 0.01, 0.1],\n","}\n","\n","# Results list to store each iteration's data\n","results = []\n","\n","# Perform GridSearchCV with error_score='raise'\n","grid = GridSearchCV(estimator=model, param_grid=param_grid, cv=3, error_score='raise')\n","try:\n","    grid_result = grid.fit(X_train, y_train)\n","\n","    # Get the best model and its accuracy\n","    best_model = grid_result.best_estimator_\n","    best_accuracy = grid_result.best_score_\n","    best_params = grid_result.best_params_\n","\n","    # Store results in the list\n","    results.append({\n","        'Hidden_Layer_Sizes': best_params['hidden_layer_sizes'],\n","        'Activation': best_params['activation'],\n","        'Dropout_Rate': best_params['dropout_rate'],\n","        'Learning_Rate': best_params['learning_rate'],\n","        'Training_Accuracy': best_accuracy,\n","        'Testing_Accuracy': best_model.score(X_test, y_test)\n","    })\n","\n","    # Convert the list to a DataFrame\n","    results_df = pd.DataFrame(results)\n","\n","    # Save the DataFrame to a CSV file\n","    results_df.to_csv('hyperparameter_results.csv', index=False)\n","\n","except Exception as e:\n","    print(\"Error occurred during GridSearchCV:\", str(e))\n","\"\"\""]},{"cell_type":"code","execution_count":131,"metadata":{"executionInfo":{"elapsed":259,"status":"ok","timestamp":1689643027739,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"VrX-Ry56dZDQ"},"outputs":[],"source":["input_shape = X_train.shape[1]\n","num_classes = len(np.unique(y_train))\n","\n","model = Sequential([\n","    Dense(64, activation='relu'),\n","    BatchNormalization(),\n","    Dropout(0.5),\n","    Dense(128, activation='relu'),\n","    BatchNormalization(),\n","    Dropout(0.5),\n","    Dense(32, activation='relu'),\n","    BatchNormalization(),\n","    Dropout(0.5),\n","    Dense(num_classes, activation='softmax')\n","])\n","\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vGv_B9gdd4yA"},"outputs":[],"source":["# Compile the model\n","model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])\n","\n","# Fit the model to the training data\n","model.fit(X_train, y_train, batch_size=8, epochs=100, verbose=1)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"UpiSxmIQd6Sb"},"outputs":[],"source":["# Evaluate the model on the testing data\n","loss, accuracy = model.evaluate(X_test, y_test)\n","\n","print(\"Testing Accuracy:\", accuracy)"]},{"cell_type":"code","execution_count":136,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":180,"status":"ok","timestamp":1689643316714,"user":{"displayName":"Zarya Amin","userId":"00381040780052705520"},"user_tz":300},"id":"DnsbY3UIfdhS","outputId":"492bf96f-9799-43b4-9d35-105482f821bb"},"outputs":[{"name":"stdout","output_type":"stream","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","fatal: Unable to read current working directory: Transport endpoint is not connected\n"]}],"source":["!git status"]}],"metadata":{"colab":{"authorship_tag":"ABX9TyNH9L611TIMqjHXZi4JuRRj","mount_file_id":"1K4x9qiERmw_caIw3YMu17mct8izpcloD","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"name":"python"}},"nbformat":4,"nbformat_minor":0}