(3375, 3695, 1)
(3375, 27)
Traceback (most recent call last):
  File "DEFUNCT_train_cnn.py", line 43, in <module>
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=lr),loss=tf.keras.losses.CategoricalCrossEntropy(),metrics=['accuracy'])
AttributeError: module 'keras.api._v2.keras.losses' has no attribute 'CategoricalCrossEntropy'